import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ weight: ["300", "500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>muhammadoka.dev</title>
      </head>
      <body className={`${poppins.className} bg-gradient-to-r from-stone-700 to-stone-900 text-white h-dvh flex flex-col`}>
        {children}
      </body>
    </html >
  );
}
